apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snorootcontainer
spec:
  crd:
    spec:
      names:
        kind: K8sNoRootContainer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snorootcontainer
        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not container.securityContext.runAsNonRoot
          msg := sprintf(
            "POLICY VIOLATION: Container '%v' must not run as root",
            [container.name]
          )
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoRootContainer
metadata:
  name: no-root-containers
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
